version: '3.8'

services:
  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/backend/static      # Persistent static files
      - media_volume:/app/backend/media        # Persistent media files
      - sqlite_data:/app/backend/db.sqlite3    # Persistent SQLite database file
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "80:80"
    depends_on:
      - web

# Volumes for persistent data
volumes:
  static_volume:
  media_volume:
  sqlite_data:    # Persistent SQLite database file
