version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # environment:
    #   - DEBUG=False
    #   - DJANGO_ALLOWED_HOSTS=43.204.219.82
  frontend:
    build: ./frontend
    ports:
      - "80:80"