version: "3.9"
services:
  backend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media  # Map backend's media directory to Nginx container
      - ./backend/staticfiles:/app/static  # Map backend's media directory to Nginx container
    command: >
      bash -c "
        pip install -r requirements.txt &&
        gunicorn backend.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=43.204.219.82

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      bash -c "
        npm install &&
        npm run build
      "
    depends_on:
      - backend  # Ensure frontend waits for backend to be ready

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx config for static and media files
      - ./backend/media:/app/media  # Ensure Nginx can access media files
      - ./backend/staticfiles:/app/static
    ports:
      - "80:80"
    depends_on:
      - frontend  # Ensure NGINX starts after frontend
