version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Make sure your Django container has access to the app code
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=43.204.219.82

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend  # Ensure frontend waits for backend to be ready
