version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/staticfiles:/app/staticfiles  # Mount static files
      - ./backend/mediafiles:/app/mediafiles    # Mount media files
      - ./backend/db.sqlite3:/app/db.sqlite3    # Persist SQLite database

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html   # Serve static React files
      - ./nginx.conf:/etc/nginx/nginx.conf      # Custom Nginx config
      - ./backend/staticfiles:/usr/share/nginx/html/static
      - ./backend/mediafiles:/usr/share/nginx/html/media
      - ./backend/db.sqlite3:/app/db.sqlite3    # Persist SQLite database
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
