# Generated by Django 5.1.4 on 2024-12-27 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsApp', '0002_country_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('caption', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdsApp.country')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdsApp.state')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdsApp.category')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdsApp.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
