# Generated by Django 5.1.4 on 2024-12-29 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsApp', '0003_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('Ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdsApp.ads')),
            ],
        ),
    ]
