# Generated by Django 5.1.4 on 2024-12-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsApp', '0004_adsimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
