# Generated by Django 5.1.4 on 2025-01-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsApp', '0006_ads_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsimages',
            name='url',
        ),
        migrations.AddField(
            model_name='adsimages',
            name='image',
            field=models.ImageField(null=True, upload_to='ads/images/'),
        ),
    ]
