# Generated by Django 5.1.4 on 2025-01-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsApp', '0007_remove_adsimages_url_adsimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsimages',
            name='Ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_images', to='AdsApp.ads'),
        ),
    ]
