# Generated by Django 5.1.4 on 2024-12-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
